version: "2"
services:
  cpp_server:
    container_name: cpp_server
    volumes:
      - "interop-volume:/var/interop-volume"
      - "./cpp/src:/usr/src"
    build:
      context: ./cpp
  python_client:
    container_name: python_client
    volumes:
      - "interop-volume:/var/interop-volume"
      - "./python/src:/usr/src"
    build:
      context: ./python
    depends_on:
      - cpp_server
volumes:
  interop-volume: